[package]
name = "image-compresser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitstream-io = "2.3.0"
image = "0.25.1"
rand = "0.8.5"
